<?php

/**
 * @file
 * Handy procedural wrapper code and potential hook implementations.
 */

use Drupal\drupal_yext\Yext\Yext;

/**
 * Implements hook_requirements().
 */
function drupal_yext_requirements($phase) {
  return Yext::instance()->hookRequirements($phase);
}

/**
 * Handy wrapper around Yext::instance()->importSome().
 */
function drupal_yext_import_some() {
  Yext::instance()->importSome();
}
