target_node_type: article
_core:
  default_config_hash: Yyq6X2OEG1oU5dB_9OJuyZwsZQNY4lIduQVikZ8dUHY
target_unique_id_field: field_yext_unique_id
field_mapping: ''
field_mapping_raw: field_yext_raw
field_mapping_geo: field_geofield
field_mapping_bio: body
field_mapping_headshot: field_yext_headshot
target_unique_last_updated_field: field_yext_last_updated
